<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PersonUI.Tests/**" />
    <Content Remove="PersonUI.Tests/**" />
    <EmbeddedResource Remove="PersonUI.Tests/**" />
    <None Remove="PersonUI.Tests/**" />

    <Compile Remove="PersonUI.E2E.Tests/**" />
    <Content Remove="PersonUI.E2E.Tests/**" />
    <EmbeddedResource Remove="PersonUI.E2E.Tests/**" />
    <None Remove="PersonUI.E2E.Tests/**" />
  </ItemGroup>

</Project>
